// Code generated by mockery v2.43.0. DO NOT EDIT.

package sophrosyne

import mock "github.com/stretchr/testify/mock"

// MockDatastoreError is an autogenerated mock type for the DatastoreError type
type MockDatastoreError struct {
	mock.Mock
}

type MockDatastoreError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatastoreError) EXPECT() *MockDatastoreError_Expecter {
	return &MockDatastoreError_Expecter{mock: &_m.Mock}
}

// Code provides a mock function with given fields:
func (_m *MockDatastoreError) Code() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDatastoreError_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type MockDatastoreError_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *MockDatastoreError_Expecter) Code() *MockDatastoreError_Code_Call {
	return &MockDatastoreError_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *MockDatastoreError_Code_Call) Run(run func()) *MockDatastoreError_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatastoreError_Code_Call) Return(_a0 string) *MockDatastoreError_Code_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatastoreError_Code_Call) RunAndReturn(run func() string) *MockDatastoreError_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields:
func (_m *MockDatastoreError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDatastoreError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockDatastoreError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockDatastoreError_Expecter) Error() *MockDatastoreError_Error_Call {
	return &MockDatastoreError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockDatastoreError_Error_Call) Run(run func()) *MockDatastoreError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatastoreError_Error_Call) Return(_a0 string) *MockDatastoreError_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatastoreError_Error_Call) RunAndReturn(run func() string) *MockDatastoreError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatastoreError creates a new instance of MockDatastoreError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatastoreError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatastoreError {
	mock := &MockDatastoreError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
